[project]
name = "dax-formatter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.4",
    "ruff>=0.12.0",
]

[project.scripts]
daxfmt = "daxfmt.main:main"
